server:
  port: 7001
eureka:
  instance:
    hostname: localhost  #eureka服务的实例名称
  client:
    #eureka server 不将自己注册到注册中心
    register-with-eureka: false
    #fasle表示自己就是注册中心，职责是维护服务实例，而不需要去检索服务
    fetch-registry: false
    #Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone:  http://${eureka.instance.hostname}:${server.port}/eureka/

