server:
  port: 7001
  
eureka:
  instance:
    hostname: eureka7001.com  #eureka服务的实例名称
  client:
    #eureka service 不将自己注册到注册中心
    register-with-eureka: false
    #fasle表示自己就是注册中心，职责是维护服务实例，而不需要去检索服务
    fetch-registry: false
    #Server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/
    #      defaultZone: http://${eureka.instance.hostname}:${service.port}/eureka/
  server:
#    enable-self-preservation: false  #关闭自我保护机制，保证不可用服务被及时剔除
    eviction-interval-timer-in-ms: 20
spring:
  application:
    name: eurekaserver7001